feat: #89 Add Modal component
tritonJS826/masters-way pull request #110
Opened 2023-10-02 11:42 UTC by Shustovsky

2023-10-02 14:58 UTC, Lelik7777 approved these changes

2023-10-03 09:00 UTC, Howl404 submitted a review, later dismissed

2023-10-03 09:00 UTC, Howl404 commented on mw-webapp/src/component/modal/ModalContent/ModalContent.tsx
> +} from "@radix-ui/react-dialog";
Here too

2023-10-03 09:01 UTC, tritonJS826 requested changes

2023-10-03 09:01 UTC, tritonJS826 commented on mw-webapp/src/component/modal/ModalContent/ModalContent.tsx
> +  children: ReactElement<HTMLElement>;
use PropsWithChildren generic

2023-10-03 09:01 UTC, tritonJS826 commented on mw-webapp/src/component/modal/ModalTrigger/ModalTrigger.tsx
> +  children: ReactElement<HTMLElement>;
use PropsWithChildren generic

2023-10-03 09:22 UTC, Shustovsky commented on mw-webapp/src/component/modal/Modal.tsx
> +import {Root as DialogRoot} from "@radix-ui/react-dialog";
my bad. now i pushed package.json )

2023-10-03 09:24 UTC, Shustovsky commented on mw-webapp/src/component/modal/Modal.tsx
> + * element and content to display within the modal.
yes, it's really redundant, I removed it.

2023-10-03 09:32 UTC, Howl404 commented on mw-webapp/src/component/modal/Modal.tsx
> +import {Root as DialogRoot} from "@radix-ui/react-dialog";
And what about pnpm lock?

2023-10-03 11:42 UTC, Shustovsky commented on mw-webapp/src/component/modal/ModalContent/ModalContent.tsx
> +  children: ReactElement<HTMLElement>;
I hope I did it right)

2023-10-03 11:42 UTC, Shustovsky commented on mw-webapp/src/component/modal/ModalTrigger/ModalTrigger.tsx
> +  children: ReactElement<HTMLElement>;
I hope I did it right)

2023-10-03 11:45 UTC, Shustovsky commented on mw-webapp/src/component/modal/Modal.tsx
> +import {Root as DialogRoot} from "@radix-ui/react-dialog";
added it too)

2023-10-03 11:52 UTC, Shustovsky commented on mw-webapp/src/component/modal/ModalContent/ModalContent.tsx
> + * Displays the content within a modal.
It's just a container for content. I have corrected the description

2023-10-03 14:31 UTC, SergioAJS requested changes

2023-10-03 14:31 UTC, SergioAJS commented on mw-webapp/src/component/modal/ModalTrigger/ModalTrigger.tsx
> +};
```suggestion
  return (
    <DialogTrigger asChild>
      {props.children}
    </DialogTrigger>
  );
};
```

2023-10-04 08:14 UTC, Shustovsky commented on mw-webapp/src/component/modal/ModalTrigger/ModalTrigger.tsx
> +};
done)

2023-10-04 08:34 UTC, Shustovsky commented on mw-webapp/src/component/modal/ModalTrigger/ModalTrigger.tsx
- I added the ability to open the Model programmatically using hooks. please look at the changes, maybe this will be enough?

- DialogTrigger and DialogRoot are designed to manage complex state and interaction related to modal windows, including accessibility support. If I use callbacks, I would have to manually manage these interactions and state changes, which can lead to errors and not provide the same level of availability support.

- ModalTrigger simplifies the process of handling interactions with modal windows and isolates them within each DialogRoot. This allows you to have multiple modal windows with their own triggers on the same page without conflicts.

2023-10-04 08:38 UTC, SergioAJS approved these changes

2023-10-06 06:32 UTC, Shustovsky commented on mw-webapp/src/component/modal/ModalContent/ModalContent.tsx
> +export const ModalContent = <T extends HTMLElement>(props: PropsWithChildren<ModalContentProps<T>>) => {
understood) I remove ModalContentProps and ModalTriggerProps)

2023-10-09 11:29 UTC, Shustovsky commented on mw-webapp/src/component/modal/Modal.tsx
> + * A component that creates a modal dialog.
fix descriptions. made it shorter, like everywhere else

2023-10-09 11:40 UTC, Shustovsky commented on mw-webapp/src/component/modal/Modal.tsx
> +  open?: boolean;
I think if there is such a need, you can use React Developer Tools and change the state
![image](https://github.com/tritonJS826/masters-way/assets/99250085/1dcbd869-0878-414e-b606-7c1bff712e84)

2023-10-10 05:10 UTC, tritonJS826 approved these changes

2023-10-10 07:15 UTC, merged