fix: #1095 Description error tooltip text
tritonJS826/masters-way pull request #1144
Opened 2024-06-20 19:57 UTC by timoxa20

Fix Punctuation error in a sentence and an extra letter in the word

2024-06-21 06:31 UTC, Ekaterina1994 requested changes

2024-06-21 06:31 UTC, Ekaterina1994 commented on mw-webapp/src/dictionary/AllWaysPageContent.json
>          "en": "The path is abandoned if it is not completed, but has not been edited in the last 14 days",
```suggestion
        "en": "The way is abandoned if it is not completed, but has not been edited in the last 14 days",
```

2024-06-21 19:44 UTC, Ekaterina1994 commented on mw-webapp/src/dictionary/AllWaysPageContent.json
>          "en": "The path is abandoned if it is not completed, but has not been edited in the last 14 days",
Need comment

2024-06-22 06:52 UTC, timoxa20 commented on mw-webapp/src/dictionary/AllWaysPageContent.json
>          "en": "The path is abandoned if it is not completed, but has not been edited in the last 14 days",
It has been fixed.Here?

2024-06-22 13:01 UTC, Ekaterina1994 approved these changes

2024-06-22 13:03 UTC, merged