fix: #1099 User personal data: Cursor is displayed incorrectly
tritonJS826/masters-way pull request #1181
Opened 2024-06-23 18:57 UTC by timoxa20

Fix Changed the text cursor for the user block, added a cursor in the user name

2024-06-23 20:26 UTC, Ekaterina1994 requested changes

2024-06-23 20:26 UTC, Ekaterina1994 commented on mw-webapp/src/logic/userPage/UserPage.module.scss
Please check all fields in the User info section. For example email is not editable but cursor is changing

2024-06-25 13:08 UTC, timoxa20 commented on mw-webapp/src/logic/userPage/UserPage.module.scss
Fix Changed the text cursor for the body, changed cursor where it is possible to edit fields

2024-06-28 18:23 UTC, closed without merging

2024-06-28 18:24 UTC, Ekaterina1994 commented
Deprecated