Create form component
tritonJS826/masters-way pull request #121
Opened 2023-10-06 14:05 UTC by Lelik7777

2023-10-08 06:34 UTC, Howl404 requested changes

2023-10-09 07:15 UTC, Ekaterina1994 commented on mw-webapp/src/component/form/formField/FormField.tsx
> +interface FormFieldProps{
Add rule to eslint/prettier, not just add space pls

2023-10-09 12:31 UTC, Shustovsky commented on mw-webapp/src/component/form/formField/fieldContainer/FieldContainer.tsx
> +      <FormLabel>
it seems to me that this component is completely superfluous here, and you can use {Label as LabelForm} directly here

2023-10-09 12:31 UTC, Shustovsky commented on mw-webapp/src/component/form/formField/fieldContainer/formMessage/FormMessage.module.scss
> +}
please use variables

2023-10-09 12:31 UTC, Shustovsky commented on mw-webapp/src/component/form/formField/fieldContainer/formLabel/FormLabel.tsx
> +  /**
please use Eslint

2023-10-09 12:32 UTC, Shustovsky commented
can I find out why you are doing PR from your personal repository?

2023-10-09 12:33 UTC, Shustovsky commented on mw-webapp/src/router/Router.tsx
>          element={pages.users.element}
these files are not related to Create form component

2023-10-09 12:33 UTC, Shustovsky commented on mw-webapp/src/router/pages.tsx
> +  },
these files are not related to Create form component

2023-10-10 04:39 UTC, SergioAJS commented on mw-webapp/src/component/form/Form.tsx
> +          />}
Maybe it's better to use Input component from our components?
You can see it if you update your working branch with the latest changes from main branch

2023-11-05 15:25 UTC, closed without merging