feat: #1118 NoAuth All Ways scope auto tests
tritonJS826/masters-way pull request #1234
Opened 2024-07-01 14:21 UTC by EkaterinaSokolova-V

Added tests:
NoAuth_AllWaysTable_LinkToOwner
NoAuth_AllWaysTable_LinkToWay
NoAuth_AllWaysTable_LinkToMentor
NoAuth_AllWaysCardsClick

2024-07-03 17:59 UTC, Ekaterina1994 commented on mw-webapp/src/component/table/Table.tsx
> +                data-cy={props.dataCy?.dataCyTBodyTd}
Мне кажется, что лучше для каждой td задавать свой атрибут datacy. Сейчас же получается, что у всех td будет одинаковый атрибут (по значению). Если у каждой ячейки будет свой атрибут, то в тестах можно будет сразу находить нужную ячейку

2024-07-10 08:14 UTC, Ekaterina1994 requested changes

2024-07-10 08:14 UTC, Ekaterina1994 commented on mw-server/db/sqlc/job_dones.query.sql.go
Для тестов нужно было удалить файлы из mw-server?

2024-07-10 08:14 UTC, Ekaterina1994 commented on mw-webapp/cypress/e2e/allWays.cy.ts
> +
Проверка по индексу выглядит очень подозрительно

2024-07-10 08:14 UTC, Ekaterina1994 commented on mw-webapp/cypress/e2e/allWays.cy.ts
> +    const ownerHeaderIndex = 4;
Последователность колонок может меняться. И индексы будут меняться. Мне кажется искать элемент по индексу не самой хорошей идеей. В дальнейшем возможны баги

2024-07-10 08:14 UTC, Ekaterina1994 commented on mw-webapp/cypress/e2e/allWays.cy.ts
> +        Math.floor(totalWays / 2),
Почему в переменной масив индексов пути нужно делить кличество всех путей на 2? Очень сложная и непрозрачная логика(

2024-07-10 08:14 UTC, Ekaterina1994 commented on mw-webapp/cypress/e2e/allWays.cy.ts
> +    const rowIndex = 0;
Правильно ли понимаю, что проверяеься только первый ряд в таблице так как идекс ряда === 0?

2024-07-10 08:14 UTC, Ekaterina1994 commented on mw-webapp/cypress/e2e/header.cy.ts
> +        cy.request('GET', 'http://localhost:8000/api/dev/reset-db');
Не понимаю зачем после каждого теста очищать полностью БД?

2024-07-10 08:14 UTC, Ekaterina1994 commented on mw-webapp/cypress/e2e/header.cy.ts
> +        cy.request('GET', 'http://localhost:8000/api/dev/reset-db');
Если нужно удалить одного пользователя, давайте создадим запрос на удаление конкретного юзера, а не будем удалять всю БД

2024-07-10 08:14 UTC, Ekaterina1994 commented on mw-webapp/cypress/fixtures/testUserDataFixture.json
> +    "userUrlPattern": "\\/user\\/[0-9a-f]{8}-([0-9a-f]{4}-){3}[0-9a-f]{12}$",
Это регулярное выражение не проверяет  совпадение по урлу, а только проверяет правильное количесто символов между '-'. Так надо?

2024-07-10 08:14 UTC, Ekaterina1994 commented on mw-webapp/src/component/table/Table.tsx
> +                data-cy={props.dataCy?.dataCyTBodyTd}
Не увидела изменений, возможно у меня что-то не отображается

2024-07-10 09:33 UTC, EkaterinaSokolova-V commented on mw-server/db/sqlc/job_dones.query.sql.go
После добавления путей в reset_db.query.sql и команды sqlc generate -f sqlc.yaml изменилось 3 файла: db.go, job_dones.query.sql.go и reset_db.query.sql.go; уточнила у бэкэндеров, сказали, что коммитить надо все файлы.

2024-07-10 09:38 UTC, EkaterinaSokolova-V commented on mw-webapp/cypress/e2e/allWays.cy.ts
> +    const ownerHeaderIndex = 4;
В предыдущих версиях так и было (сначала искался номер колонки с нужным заголовком), но т.к. номер колонки не динамический, Виктор пердложил использовать переменную.

2024-07-10 09:43 UTC, EkaterinaSokolova-V commented on mw-webapp/cypress/e2e/allWays.cy.ts
> +        Math.floor(totalWays / 2),
Проверяю пути на границах и посередине, можно изменить на рандомный путь из этого интервала.

2024-07-10 09:46 UTC, EkaterinaSokolova-V commented on mw-webapp/cypress/e2e/allWays.cy.ts
> +    const rowIndex = 0;
Этот тест аналогичен предыдущему NoAuth_AllWaysTable_LinkToOwner, не передела его пока.

2024-07-10 09:47 UTC, EkaterinaSokolova-V commented on mw-webapp/cypress/e2e/header.cy.ts
> +        cy.request('GET', 'http://localhost:8000/api/dev/reset-db');
Да, был от меня запрос на удаление пользователя, предложено такое решение.

2024-07-10 09:52 UTC, EkaterinaSokolova-V commented on mw-webapp/cypress/fixtures/testUserDataFixture.json
> +    "userUrlPattern": "\\/user\\/[0-9a-f]{8}-([0-9a-f]{4}-){3}[0-9a-f]{12}$",
При "фэйковом" логине он генерится заново каждый раз и не возможно  проверить совпадение символов.

2024-07-10 10:01 UTC, EkaterinaSokolova-V commented on mw-webapp/cypress/e2e/allWays.cy.ts
> +
Не придумала лучшего решения. Буду благодарна за идеи, как это сделать по-другому.

2024-07-10 10:02 UTC, EkaterinaSokolova-V commented on mw-webapp/cypress/e2e/allWays.cy.ts
> +
Не придумала лучшего решения. Буду благодарна за идеи, как это сделать по-другому.

2024-07-10 10:04 UTC, EkaterinaSokolova-V commented on mw-webapp/src/component/table/Table.tsx
> +                data-cy={props.dataCy?.dataCyTBodyTd}
В результате не придумала, как это сделать, поэтому ищется индекс td для сравнения с индексом заголовка столбца.

2024-07-11 09:40 UTC, tritonJS826 commented on mw-webapp/cypress/e2e/header.cy.ts
> +        cy.request('GET', 'http://localhost:8000/api/dev/reset-db');
я за резет бд до нормального состояния, ручное удаление пользоватедей слишком низкоуровневая операция. Но ссылка должна быть не строкой захардкожена, а динамической (bp env), а то в контейнерах не будет работать или на других окружениях

2024-07-11 09:40 UTC, tritonJS826 commented on mw-webapp/cypress/e2e/allWays.cy.ts
> +      cy.go('back');
go back может приводить к потенциальным проблемам, если тесты усложняться, нельзя ли использовать абсолютный url для навигации?

2024-07-11 14:27 UTC, EkaterinaSokolova-V commented on mw-webapp/cypress/e2e/header.cy.ts
> +        cy.request('GET', 'http://localhost:8000/api/dev/reset-db');
done

2024-07-11 14:27 UTC, EkaterinaSokolova-V commented on mw-webapp/cypress/e2e/allWays.cy.ts
> +      cy.go('back');
done

2024-07-11 14:48 UTC, EkaterinaSokolova-V commented on mw-webapp/cypress/e2e/allWays.cy.ts
> +    const rowIndex = 0;
done

2024-07-11 14:48 UTC, EkaterinaSokolova-V commented on mw-webapp/cypress/e2e/allWays.cy.ts
> +    const ownerHeaderIndex = 4;
done

2024-07-11 14:48 UTC, EkaterinaSokolova-V commented on mw-webapp/cypress/e2e/allWays.cy.ts
> +
done

2024-07-11 14:49 UTC, EkaterinaSokolova-V commented on mw-webapp/src/component/table/Table.tsx
> +                data-cy={props.dataCy?.dataCyTBodyTd}
done

2024-07-12 08:54 UTC, Ekaterina1994 approved these changes

2024-07-12 19:30 UTC, tritonJS826 approved these changes

2024-07-12 19:30 UTC, merged