feat: #85 Create input component
tritonJS826/masters-way pull request #126
Opened 2023-10-07 14:48 UTC by Ekaterina1994

2023-10-07 14:58 UTC, tritonJS826 approved these changes

2023-10-07 14:58 UTC, tritonJS826 commented on mw-webapp/src/component/input/Input.module.scss
> +  width: $input-width;
strange global variable

2023-10-07 14:58 UTC, tritonJS826 commented on mw-webapp/src/component/input/Input.tsx
> +   * The event handler
it does not handle events

2023-10-07 14:58 UTC, tritonJS826 commented on mw-webapp/src/component/input/Input.tsx
> +   * @default InputMode.text
why not to use link here

2023-10-07 15:12 UTC, Ekaterina1994 commented on mw-webapp/src/component/input/Input.module.scss
> +  width: $input-width;
Changed to width-primary

2023-10-07 15:15 UTC, Ekaterina1994 commented on mw-webapp/src/component/input/Input.tsx
> +   * The event handler
Changed

2023-10-07 15:15 UTC, Ekaterina1994 commented on mw-webapp/src/component/input/Input.tsx
> +   * @default InputMode.text
ADded

2023-10-08 04:38 UTC, SergioAJS commented on mw-webapp/src/component/table/LoadingContext.tsx
>  import React, {createContext, PropsWithChildren, useContext, useState} from "react";
Do we need to explicitly import react?

2023-10-08 04:38 UTC, SergioAJS commented on mw-webapp/src/component/input/Input.tsx
> +import React, {HTMLInputTypeAttribute} from "react";
Do we need to explicitly import react?

2023-10-08 05:31 UTC, Howl404 approved these changes

2023-10-08 05:55 UTC, Ekaterina1994 commented on mw-webapp/src/component/table/LoadingContext.tsx
>  import React, {createContext, PropsWithChildren, useContext, useState} from "react";
Deleted in all components, thanks

2023-10-08 05:55 UTC, Ekaterina1994 commented on mw-webapp/src/component/input/Input.tsx
> +import React, {HTMLInputTypeAttribute} from "react";
Deleted in components, thanks

2023-10-08 06:34 UTC, SergioAJS approved these changes

2023-10-08 06:42 UTC, Howl404 requested changes

2023-10-08 06:42 UTC, Howl404 commented on mw-webapp/src/component/input/Input.tsx
> +export const Input: React.FC<InputProps> = (props: InputProps) => {
```suggestion
export const Input = (props: InputProps) => {
```

2023-10-08 06:42 UTC, Howl404 commented on mw-webapp/src/component/table/LoadingContext.tsx
> +export const LoadingProvider: React.FC<PropsWithChildren> = (props: PropsWithChildren) => {
```suggestion
export const LoadingProvider = (props: PropsWithChildren) => {
```

2023-10-08 08:00 UTC, Ekaterina1994 commented on mw-webapp/src/component/table/LoadingContext.tsx
> +export const LoadingProvider: React.FC<PropsWithChildren> = (props: PropsWithChildren) => {
Why

2023-10-08 08:00 UTC, Ekaterina1994 commented on mw-webapp/src/component/input/Input.tsx
> +export const Input: React.FC<InputProps> = (props: InputProps) => {
Why

2023-10-08 08:53 UTC, Howl404 commented on mw-webapp/src/component/input/Input.tsx
> +export const Input: React.FC<InputProps> = (props: InputProps) => {
Unnecessary type

2023-10-08 09:40 UTC, Ekaterina1994 commented on mw-webapp/src/component/input/Input.tsx
> +export const Input: React.FC<InputProps> = (props: InputProps) => {
Deleted in all componets

2023-10-08 09:40 UTC, Ekaterina1994 commented on mw-webapp/src/component/table/LoadingContext.tsx
> +export const LoadingProvider: React.FC<PropsWithChildren> = (props: PropsWithChildren) => {
Deleted in all componets

2023-10-08 09:52 UTC, Howl404 approved these changes

2023-10-08 10:11 UTC, merged