feat: #1344 update readme mw-webapp
tritonJS826/masters-way pull request #1535
Opened 2024-09-06 16:04 UTC by AKiroi

update README.md in mw-webapp

2024-09-09 19:12 UTC, tritonJS826 requested changes
Looks like duplication of root readme, why do we need it?

2024-09-14 11:38 UTC, tritonJS826 commented on mw-webapp/README.md
> +- [Docker Compose](https://docs.docker.com/compose/) v1.29.2
```suggestion
```

2024-09-14 11:38 UTC, tritonJS826 commented on mw-webapp/README.md
> +   ```
```suggestion
```

2024-09-14 11:39 UTC, tritonJS826 commented on mw-webapp/README.md
> +
```suggestion
- Run component tests:
  ```sh
  pnpm cypress:component:run
  ```

- Run component tests ui mode:
  ```sh
  pnpm cypress:component:open
  ```

```

2024-09-14 11:42 UTC, tritonJS826 commented on mw-webapp/README.md
> +  ```
```suggestion
- Run component tests:
  ```sh
  pnpm cypress:component:run
  ``` 
- Run component tests ui mode:
  ```sh
  pnpm cypress:component:open
  ``` 

- Run end-to-end tests:
  ```sh
  pnpm cypress:e2e:run
  ```
 - Run end-to-end tests ui mode:
  ```sh
  pnpm cypress:e2e:open
  ```
```

2024-09-14 11:45 UTC, tritonJS826 commented on mw-webapp/README.md
> +
add all and only module-specific scripts (cypress:open, serve etc)

2024-09-14 11:45 UTC, tritonJS826 commented on mw-webapp/README.md
> +  pnpm cypress:component:run
sorry I broke it with github suggestion :)

2024-09-18 09:01 UTC, Ekaterina1994 commented
Need to add info that command pnpm run api:generate works only with pnpm serve, with pnpm start it doesn't works

2024-09-24 12:53 UTC, closed without merging