refactor: #162 change width for table header
tritonJS826/masters-way pull request #172
Opened 2023-10-29 15:50 UTC by MaratReactJs

2023-10-29 15:55 UTC, Howl404 approved these changes

2023-10-29 19:22 UTC, Ekaterina1994 requested changes

2023-10-29 19:22 UTC, Ekaterina1994 commented on mw-webapp/src/component/table/Table.module.scss
>    border: 1px solid #dddddd;
horror

2023-10-30 18:02 UTC, Ekaterina1994 requested changes
please check styles

2023-10-30 18:51 UTC, MaratReactJs commented on mw-webapp/src/component/table/Table.module.scss
>    border: 1px solid #dddddd;
moved global styles to variables.scss

2023-10-30 18:54 UTC, Ekaterina1994 approved these changes

2023-10-30 20:27 UTC, tritonJS826 approved these changes

2023-10-30 20:29 UTC, merged