feat: #192 Add possibility to edit own way
tritonJS826/masters-way pull request #205
Opened 2023-11-10 19:04 UTC by Ekaterina1994

2023-11-11 14:19 UTC, tritonJS826 requested changes

2023-11-11 14:19 UTC, tritonJS826 commented on mw-webapp/src/logic/waysTable/renderCellValue/helpers/updateCell.ts
> +    updateCells(`update${arrayItem.constructor.name}`, text, arrayItem.uuid);
no template strings for parameters to update something, in is not maintainable

2023-11-11 14:19 UTC, tritonJS826 commented on mw-webapp/src/logic/waysTable/renderCellValue/helpers/updateCell.ts
> +  callback: (arg: boolean) => void,
what does `arg` mean?

2023-11-11 14:19 UTC, tritonJS826 commented on mw-webapp/src/logic/waysTable/renderCellValue/helpers/updateCell.ts
> +  callback: (arg: boolean) => void,
call back is not described meanin of this function

2023-11-11 14:19 UTC, tritonJS826 commented on mw-webapp/src/logic/waysTable/renderCellValue/helpers/updateCell.ts
> +  columnName?: keyof ColumnNameProps,
wrong interface
there is no possibilities to have all this optional parameters

2023-11-11 14:19 UTC, tritonJS826 commented on mw-webapp/src/logic/waysTable/renderCellValue/helpers/updateGoalPreview.ts
> +export const updateGoalPreview = async (description: string, uuid: string) => {
make param oblject

2023-11-11 14:19 UTC, tritonJS826 commented on mw-webapp/src/logic/waysTable/renderCellValue/helpers/updateName.ts
> +export const updateName = async (updatedText: string, uuid: string, columnName: keyof ColumnNameProps) => {
?

2023-11-11 14:19 UTC, tritonJS826 commented on mw-webapp/src/logic/waysTable/renderCellValue/renderCellValue.tsx
> +  isCompleted: boolean;
!

2023-11-11 14:19 UTC, tritonJS826 commented on mw-webapp/src/logic/waysTable/renderCellValue/renderCellValue.tsx
> +export const renderCellValue = (props: CellItemProps) => {
renderEditableText
why it is not a component

2023-11-14 15:23 UTC, SergioAJS commented
I've noticed that when I double-click on a value to change it, then exit edit mode without changing the value - firestore requests occur. Is it possible to make it so that before the request a check is performed to see if the value has changed, and if it hasn't, the request is not sent?

2023-11-14 15:24 UTC, SergioAJS reviewed
I've noticed that when I double-click on a value to change it, then exit edit mode without changing the value - firestore requests occur. Is it possible to make it so that before the request a check is performed to see if the value has changed, and if it hasn't, the request is not sent?

2023-11-19 15:51 UTC, closed without merging