fix: #548 get rid of errors in thr console
tritonJS826/masters-way pull request #562
Opened 2024-02-22 18:29 UTC by AKiroi

get rid of errors in thr console

2024-02-22 20:03 UTC, Ekaterina1994 reviewed
Please check all pages in console. I remember that there were also other errors)

2024-02-23 05:42 UTC, tritonJS826 requested changes

2024-02-23 05:42 UTC, tritonJS826 commented on mw-webapp/src/hooks/usePersistanceState.tsx
> -  }, [params.storedDataValidator]);
Are you sure nothing is broken?

2024-02-23 05:43 UTC, tritonJS826 commented
Looks like these changes broke business logic. Be careful. I will send you a video

2024-02-23 23:18 UTC, AKiroi commented
fixex this mistakes 
![image](https://github.com/tritonJS826/masters-way/assets/112805668/63c98ff5-2141-4bb0-9a74-e23aa4c240fc)

2024-02-23 23:21 UTC, AKiroi commented
need to add typization to dependencies in usePersistanceState

2024-02-24 16:11 UTC, tritonJS826 approved these changes

2024-02-25 09:35 UTC, merged